- name: Sync Storage
  hosts: localhost
  vars_files:
    - ../../config/global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/user/login.yml"
    - import_tasks: "{{GLOBAL.baseDir}}/task/storage/sync_storage.yml"
