---

# Required Parameters:
#   pgName:            protection group name
#   volumes:           a list of primary volumes
#
# Examples:
#   --extra-vars '{"pgName": "pg1", "volumes": ["DJ_AT_0000", "DJ_AT_0001"]}'
#

- name: Create Protection Group
  hosts: localhost
  vars_files:
    - ../../../global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: ../check_volume_affinity.yml

    - import_tasks: ../login_storage.yml

    - name: Check PG name conflicts
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/api/v2/protectgroup?filter=protectGroupName%3A%3A{{pgName|urlencode}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: ExistPG
      failed_when: ExistPG.json.data is defined 

    - name: Create PG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/api/v2/protectgroup"
        method: POST
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
        body_format: json
        body:
          protectGroupName: "{{ pgName }}"
      register: PG

    - name: Get PG ID
      set_fact:
        pgId: "{{ PG.json.data.protectGroupId }}"

    - name: Show PG ID
      debug:
        msg: 
          pgId: "{{ pgId }}"

    - name: Add Volumes to PG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/api/v2/protectgroup/associate"
        method: POST
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
        body_format: json
        body:
          protectGroupId: "{{ pgId }}"
          ASSOCIATEOBJTYPE: 11              # 11: LUN
          ASSOCIATEOBJID: "{{ item }}"
      register: ADD_VOLUMES
      with_items: "{{ volumeIds }}"

    - name: Show Add Volume Results
      vars:
        queryError: "[*].json.error"
      debug:
        msg: "{{ ADD_VOLUMES.results | json_query(queryError) }}"