---

# Required Parameters:
#   pgName:            protection group name
#   volumes:           a list of primary volumes
#
# Examples:
#   --extra-vars '{"pgName": "pg1", "volumes": ["DJ_AT_0002", "DJ_AT_0003"]}'
#

- name: Remove Volumes From Protection Group
  hosts: localhost
  vars_files:
    - ../../../global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: ../check_volume_affinity.yml

    - import_tasks: ../login_storage.yml

    - name: Query PG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/api/v2/protectgroup?filter=protectGroupName%3A%3A{{pgName|urlencode}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: PG
      failed_when: PG.json.data is not defined

    - name: Get PG ID
      vars:
        pg: "{{ PG.json.data[0] }} "
      set_fact:
        pgId: "{{ pg.protectGroupId }}"

    - name: Show PG ID
      debug:
        msg: 
          pgId: "{{ pgId }}"

    - name: Remove Volumes from PG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/api/v2/protectgroup/associate?protectGroupId={{pgId}}&ASSOCIATEOBJTYPE=11&ASSOCIATEOBJID={{item}}"
        method: DELETE
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: REMOVE_VOLUMES
      with_items: "{{ volumeIds }}"

    - name: Show Remove Volume Results
      vars:
        queryError: "[*].json.error"
      debug:
        msg: "{{ REMOVE_VOLUMES.results | json_query(queryError) }}"