---

- name: GET Relation by ID
  hosts: localhost
  vars_files:
    - ../global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: ../user/login.yml
    
    - name: Get Relation
      uri:
        url: "https://{{DJ.host}}:{{DJ.port}}/rest/{{URI.relations}}/{{relationName}}/instances/{{instanceId}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{DJ.token}}"
      register: RELATION

    - name: Show Relation
      debug:
        msg: "{{ RELATION.json }}"
