- name: List Instances
  hosts: localhost
  vars_files:
    - ../../config/global.yml   
  gather_facts: yes
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/user/login.yml" 
    - import_tasks: "{{GLOBAL.baseDir}}/task/cmdb/list_instances.yml"
