---

dummy:

dataset: "perf-storage-pool"
query:
  timeRange:
    beginTime: 1574265600000
    endTime: 1574651742000
    granularity: "auto"
  filters:
    dimensions:
      - field: "dimensions.object.name"
        values:
          - "pool"
  dimensions:
    - field: "dimensions.object.name"
      index: 1
    - field: "timestamp"
      index: 2
  metrics:
    - field: "metrics.throughput"
      aggType: "sum"
    - field: "metrics.bandwidth"
      aggType: "sum"
    - field: "metrics.responseTime"
      aggType: "avg"
