---

# Optional Parameters:
#   pageNo:         page number, default 1
#   pageSize:       page size, default: 10
#   projectName:    project name
#
# Examples:
#   --extra-vars "projectName='project1'"
#
- name: List Projects
  hosts: localhost
  vars_files:
    - ../../config/global.yml
  vars:
    pageNo: 1
    pageSize: 10
    params: "{{'limit=' + pageSize|string + '&start=' + (pageSize|int * (pageNo|int - 1) + 1) | string }}"
  gather_facts: no
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/user/login.yml"
    
    - name: Set params - projectName
      set_fact:
        params: "{{ params + '&name=' + projectName|urlencode }}"
      when: 
        - projectName is defined

    - name: List Projects
      uri:
        url: "https://{{djHost}}:{{djPort}}{{ DJSERVICE.API.projects }}?{{params}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{djToken}}"
      register: PROJECTS

    - name: Show Projects
      vars:
        objList: "{{ PROJECTS.json.projectList }}"
        totalNum: "{{ PROJECTS.json.total }}"
      debug:
        msg: 
          objList: "{{ objList }}"
          totalNum: "{{ totalNum }}"
          pageSize: "{{ pageSize }}"
          pageNo: "{{ pageNo }}"
