# Include this tasks at the end of playbooks if need to logout 
# 
# Required to load var file ../global.yml
#
# Examples:
#
#  vars_files:
#    - ../global.yml
#  tasks:
#    - import_tasks: ../user/login.yml
#
#    - import_tasks: ../user/logout.yml

- name: Logout DJ
  uri:
    url: "https://{{DJ.host}}:{{DJ.port}}/rest/{{ URI.sessions }}"
    method: DELETE
    validate_certs: no
    headers:
      Accept: "application/json"
      Content-Type: "application/json;charset=utf8"
      X-Auth-Token: "{{DJ.token}}"
