---

- name: List Indicators
  hosts: localhost
  vars_files:
    - ../global.yml
  vars:
    # Required Parameters:
    #   objType:     object type name, see ../global.yml to get supported object types in INVENTORY
    #
    # Example:
    #   --extra-vars "objType=volume"
    
    # Generated Parameters (can be overwritten):
    #   objTypeId:     object type id, see ../global.yml to get supported object types in INVENTORY.objType.objTypeId
    #
    # Examples:
    #   --extra-vars "objTypeId='1125921381679104'"
    
    objTypeId: "{{ INVENTORY[objType].objTypeId }}"    # map objType to objTypeId
  gather_facts: no
  become: no
  tasks:
    - import_tasks: ../user/login.yml
    
    - name: List Indicators
      uri:
        url: "https://{{DJ.host}}:{{DJ.port}}/rest/{{URI.perfmgr}}/obj-types/{{objTypeId}}/indicators"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{DJ.token}}"
      register: INDICATORS

    - name: Show Indicators
      debug:
        msg: "{{ INDICATORS.json }}"

    - name: Get Indicator Details
      uri:
        url: "https://{{DJ.host}}:{{DJ.port}}/rest/{{URI.perfmgr}}/indicators"
        method: POST
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{DJ.token}}"
        body_format: json
        body: "{{ INDICATORS.json.data.indicator_ids }}"
      register: DETAILS

    - name: Show Indicator Details
      debug:
        msg: "{{ DETAILS.json }}"

    - name: Generate Indicator Map
      set_fact:
          indicator_map: "{{ indicator_map|default({}) | combine( {DETAILS.json.data[item|string].indicator_name: item|string } ) }}"
      with_items: "{{INDICATORS.json.data.indicator_ids}}"

    - name: Show Indicator Map
      debug:
        msg: "{{ indicator_map }}"
