- name: Attach Volumes to Host Group
  hosts: localhost
  vars_files:
    - ../../config/global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/user/login.yml"
    - import_tasks: "{{GLOBAL.baseDir}}/task/volume/attach_volumes_to_hostgroup.yml"