---

# Required Parameters:
#   volumeName:     volume name
#
# Examples:
#   --extra-vars "volumeName='ansible'"
#
# Optional Parameters:
#   pageNo:         page number, default 1
#   pageSize:       page size, default: 10
#
# Examples:
#   --extra-vars "pageNo=1 pageSize=100 volumeName='ansible'"

- name: Get Volumes by Fuzzy Name
  hosts: localhost
  vars:
    pageNo: 1            # page number
    pageSize: 10         # page size
    pageStart: "{{ pageSize|int * (pageNo|int - 1) }}"
  vars_files:
    - ../global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: ../user/login.yml
    
    - name: List Volumes
      uri:
        url: "https://{{DJ.host}}:{{DJ.port}}/rest/{{ URI.volumes }}?limit={{pageSize}}&start={{pageStart}}&name={{volumeName|urlencode}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{DJ.token}}"
      register: VOLUMES

    - name: Show Volumes
      debug:
        msg: 
          Detail: "{{ VOLUMES.json }}"
          Matches: "{{ VOLUMES.json.volumes | json_query('[*].name') }}"
