---

# Required Parameters:
#   hostName:       host name
#
# Examples:
#   --extra-vars "hostName='test'"
#
- name: Get Hosts by Fuzzy Name
  hosts: localhost
  vars_files:
    - ../../config/global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/user/login.yml"
    
    - name: Get Hosts by Fuzzy Name
      uri:
        url: "https://{{djHost}}:{{djPort}}{{ DJSERVICE.API.hosts }}/summary"
        method: POST
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{djToken}}"
        body_format: json
        body:
          name: "{{hostName}}"
      register: HOSTS

    - name: Show Hosts
      debug:
         msg: "{{ HOSTS.json }}"
