---

# Required Parameters:
#   hostGroupName:     host group name
#
# Examples:
#   --extra-vars "hostGroupName='test'"
#
- name: Get Host Groups by Fuzzy Name
  hosts: localhost
  vars_files:
    - ../global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: ../user/login.yml
    
    - name: Get Host Groups by Fuzzy Name
      uri:
        url: "https://{{DJ.host}}:{{DJ.port}}/rest/{{ URI.hostgroups }}/summary"
        method: POST
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          X-Auth-Token: "{{DJ.token}}"
        body_format: json
        body:
          name: "{{hostGroupName}}"
      register: HOSTGROUPS

    - name: Show Host Groups
      debug:
         msg: "{{ HOSTGROUPS.json }}"
