---

# Required Parameters:
#   deviceName:        storage device name, can be replace with deviceSn
#   cgName:            consistency group name
#
# Examples:
#   --extra-vars "deviceName='storage1' cgName='cg1'"
#
# Optional Parameters:
#   deviceSn:          storage device SN
#   deletePairs:       delete pairs after remove from CG, default: yes, options: yes, no
#
# Examples:
#   --extra-vars '{"deviceSn":"12323019876312325911", "cgName":"cg1", "deletePairs": no}'
#

- name: Delete Replication Consistency Group
  hosts: localhost
  vars:
    deletePairs: yes
  vars_files:
    - ../../global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: login_storage.yml

    - name: Query Replication CG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/CONSISTENTGROUP?filter=NAME%3A%3A{{cgName|urlencode}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: ReplicationCG
      failed_when: ReplicationCG.json.data is not defined

    - name: Get Replication CG ID
      set_fact:
        cgId: "{{ ReplicationCG.json.data[0].ID }}"

    - name: Show Replication CG ID
      debug:
        msg: 
          cgId: "{{ cgId }}"

    - name: Query Replication Pairs
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/REPLICATIONPAIR?filter=CGID%3A%3A{{cgId}}"
        method: GET
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: ReplicationPairs

    - name: Get Replication Pair IDs
      vars:
        query: "[*].ID"
      set_fact:
        pairIds: "{{ ReplicationPairs.json.data | json_query(query) }}"

    - name: Show Replication Pair IDs
      debug:
        msg: 
          pairIds: "{{ pairIds }}"

    - name: Pause Replication CG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/SPLIT_CONSISTENCY_GROUP"
        method: PUT
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
        body_format: json
        body:
          ID: "{{ cgId }}"
      register: SPLIT_CG

    - name: Show Pause Results
      debug:
        msg: "{{ SPLIT_CG.json.error }}"

    - name: Remove Replication Pairs from CG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/DEL_MIRROR"
        method: PUT
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
        body_format: json
        body:
          ID: "{{ cgId }}"
          RMLIST:
            - "{{ item }}"
      register: REMOVE_PAIRS
      with_items: "{{ pairIds }}"
      when: pairIds|length > 0

    - name: Show Remove Pair Results
      vars:
        queryError: "[*].json.error"
      debug:
        msg: "{{ REMOVE_PAIRS.results | json_query(queryError) }}"
      when: pairIds|length > 0

    - name: Delete Replication CG
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/CONSISTENTGROUP/{{cgId}}"
        method: DELETE
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: DELETE_CG

    - name: Show Delete CG Results
      debug:
        msg: "{{ DELETE_CG.json.error }}"

    - name: Delete Replication Pairs
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/REPLICATIONPAIR/{{item}}"
        method: DELETE
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
      register: DELETE_PAIRS
      with_items: "{{ pairIds }}"
      when: deletePairs and pairIds|length > 0

    - name: Show Delete Pair Results
      vars:
        queryError: "[*].json.error"
      debug:
        msg: "{{ DELETE_PAIRS.results | json_query(queryError) }}"
      when: deletePairs and pairIds|length > 0

    - name: Sync Replication Pairs
      uri:
        url: "https://{{deviceHost}}:{{devicePort}}/deviceManager/rest/{{deviceSn}}/REPLICATIONPAIR/sync"
        method: PUT
        validate_certs: no
        headers:
          Accept: "application/json"
          Content-Type: "application/json;charset=utf8"
          iBaseToken: "{{ deviceToken }}"
          Cookie: "session={{ deviceSession }}"
        body_format: json
        body:
          ID: "{{ item }}"
      register: SYNC_PAIRS
      with_items: "{{ pairIds }}"
      when: not deletePairs and pairIds|length > 0

    - name: Show Sync Pair Results
      vars:
        queryError: "[*].json.error"
      debug:
        msg: "{{ SYNC_PAIRS.results | json_query(queryError) }}"
      when: not deletePairs and pairIds|length > 0