- name: Map LUNs to Host
  hosts: localhost
  vars_files:
    - ../../../config/global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/storage/oceanstor/login_storage.yml"
    - import_tasks: "{{GLOBAL.baseDir}}/task/storage/oceanstor/map_luns_to_host.yml"
