# Variables for Rundeck Workflow of project001

# KPI DB
KPIDB:
  enable: True
  host: "<KPIDB_HOST>"
  user: "<KPIDB_USER_NAME>"
  pswd: "<KPIDB_PASSWORD>"
  database: "<KPIDB>"
  table: "<KPIDB_TABLE>"

# Data Center (Site)
DC:
  MV:
    desc: "Mogliano Veneto"
  PD:
    desc: "Padova"
  AC:
    desc: "Aachen"

# Availability Zone (Room)
AZ:
  AT:
    dc: "MV"
    desc: "Mogliano Veneto - Room AT"
  BC:
    dc: "MV"
    desc: "Mogliano Veneto - Room BC"
  PD:
    dc: "PD"
    desc: "Padova - Room PD"
  I1:
    dc: "AC"
    desc: "Aachen - Room IVZ1"
  I2:
    dc: "AC"
    desc: "Aachen - Room IVZ2"

# Operating System Type
OSTYPE:
  AIX: 
    enum: 4
    djenum: "AIX"
    desc: "AIX"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  LNX:
    enum: 0
    djenum: "LINUX"
    desc: "Linux"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  LNP:
    enum: 0
    djenum: "LINUX"
    desc: "Linux on Power"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  ESX:
    enum: 7
    djenum: "VMWAREESX"
    desc: "VMware ESXi"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 255
    placeholder_scsi_id: [260, 261]
  OVM:
    enum: 12
    djenum: "ORACLE"
    desc: "Oracle VM"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 255
    placeholder_scsi_id: []
  OVS:
    enum: 13
    djenum: "ORACLE"
    desc: "Oracle VM for SPAC"
    enable: 0
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  SOL:
    enum: 2
    djenum: "SOLARIS"
    desc: "Solaris"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  WIN:
    enum: 1
    djenum: "WINDOWSSERVER2012"
    desc: "Windows"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 255
    placeholder_scsi_id: []
  XEN:
    enum: 15
    djenum: "XENSERVER"
    desc: "XenServer"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 255
    placeholder_scsi_id: []
  VIO:
    enum: 4
    djenum: "AIX"
    desc: "LPAR VIO"
    enable: 1
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  HPX:
    enum: 3
    djenum: "HPUX"
    desc: "HP-UX"
    enable: 0
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  MAC:
    enum: 6
    djenum: "MACOS"
    desc: "MAC OS"
    enable: 0
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []
  VMS:
    enum: 11
    djenum: "OPENVMS"
    desc: "OpenVMS"
    enable: 0
    min_scsi_id: 1
    max_scsi_id: 2047
    placeholder_scsi_id: []

# Replica Type
REPTYPE:
  N1: 
    metro: "N"
    level: "1"
    dr:    "N"
    dr3rd: "N"
    enum:  "N"              # No Replica
    type:  "00"             # No Replica
  N2: 
    metro: "N"
    level: "2"
    dr:    "Y"
    dr3rd: "N"
    enum:  "R"              # Replication
    type:  "HR"             # HyperReplication
  N3: 
    metro: "N"
    level: "3"
    dr:    "Y"
    dr3rd: "Y"
    enum:  "T"              # Replication with 3rd copy
    type:  "HR"             # HyperReplication
  Y1: 
    metro: "Y"
    level: "1"
    dr:    "N"
    dr3rd: "N"
    enum:  "N"
    type:  "HM"             # HyperMetro
  Y2: 
    metro: "Y"
    level: "2"
    dr:    "Y"
    dr3rd: "N"
    enum:  "R"
    type:  "H3"             # HyperMetro + HyperReplication DR Star Trio
  Y3: 
    metro: "Y"
    level: "3"
    dr:    "Y"
    dr3rd: "Y"
    enum:  "T"
    type:  "H3"             # HyperMetro + HyperReplication DR Star Trio

# Replication Mode
REPMODE:
  AR:
    enum: 2
    desc: "ASync Replication"
# SR:
#   enum: 1
#   desc: "Sync Replication"

SNAPCG:
  activated:
    enum: 43
    desc: "Activated"
  rolling_back:
    enum: 44
    desc: "Rolling Back"
  unactivated:
    enum: 45
    desc: "Unactivated"
