# Required Parameters:
#   taskId:     Task ID
#
# Optional Parameters:
#   waitSeconds:    wait seconds, default 300
#   waitInterval:   wait interval, default 5
#   checkSuccess:   check if the task success, defaut: no, options: yes/no
#
# Examples:
#   --extra-vars "taskId=bd5f2b70-d416-4d61-8e1a-f763e68dbbe1 waitSeconds=60"

- name: Wait Task Complete
  hosts: localhost
  vars_files:
    - ../../config/global.yml
  gather_facts: no
  become: no
  tasks:
    - import_tasks: "{{GLOBAL.baseDir}}/task/user/login.yml"
    - import_tasks: "{{GLOBAL.baseDir}}/task/task/wait_task_complete.yml"
